language: ruby
sudo: false
script: 'ci/travis.rb'
before_install:
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"
  - curl -L https://github.com/kr/beanstalkd/archive/v1.10.tar.gz | tar xz -C /tmp
  - cd /tmp/beanstalkd-1.10/
  - make
  - ./beanstalkd &
  - cd $TRAVIS_BUILD_DIR
before_script:
  - bundle update
cache: bundler
env:
  matrix:
    - "GEM=railties"
    - "GEM=ap"
    - "GEM=ac"
    - "GEM=am,amo,as,av,aj"
    - "GEM=ar:mysql2"
    - "GEM=ar:sqlite3"
    - "GEM=ar:postgresql"
    - "GEM=aj:integration"
    - "GEM=guides"
rvm:
  - 2.2.4
  - 2.3.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "YA1alef1ESHWGFNVwvmVGCkMe4cUy4j+UcNvMUESraceiAfVyRMAovlQBGs6\n9kBRm7DHYBUXYC2ABQoJbQRLDr/1B5JPf/M8+Qd7BKu8tcDC03U01SMHFLpO\naOs/HLXcDxtnnpL07tGVsm0zhMc5N8tq4/L3SHxK7Vi+TacwQzI="
bundler_args: --without test --jobs 3 --retry 3
services:
  - memcached
  - redis
  - rabbitmq
addons:
  postgresql: "9.4"
