language: ruby
sudo: false

cache:
  bundler: true
  directories:
    - /tmp/cache/unicode_conformance
    - /tmp/beanstalkd-1.10

services:
  - memcached
  - redis
  - rabbitmq

addons:
  postgresql: "9.4"

bundler_args: --without test --jobs 3 --retry 3
before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "travis_retry gem update --system"
  - "travis_retry gem install bundler"
  - "[ -f /tmp/beanstalkd-1.10/Makefile ] || (curl -L https://github.com/kr/beanstalkd/archive/v1.10.tar.gz | tar xz -C /tmp)"
  - "pushd /tmp/beanstalkd-1.10 && make && (./beanstalkd &); popd"

before_script:
  - bundle update

script: 'ci/travis.rb'

env:
  matrix:
    - "GEM=railties"
    - "GEM=ap"
    - "GEM=ac"
    - "GEM=ac FAYE=1"
    - "GEM=am,amo,as,av,aj"
    - "GEM=as PRESERVE_TIMEZONES=1"
    - "GEM=ar:mysql2"
    - "GEM=ar:sqlite3"
    - "GEM=ar:postgresql"
    - "GEM=aj:integration"
    - "GEM=guides"

rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4

matrix:
  include:
    # Latest compiled version in http://rubies.travis-ci.org
    - rvm: 2.3.7
      env:
        - "GEM=ar:mysql2"
      addons:
        mariadb: 10.2
    - rvm: jruby-9.1.9.0
      jdk: oraclejdk8
      env:
        - "JRUBY_OPTS='--dev -J-Xmx1024M'"
        - "GEM='ap'"
  allow_failures:
    - rvm: jruby-9.1.9.0
  fast_finish: true

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "YA1alef1ESHWGFNVwvmVGCkMe4cUy4j+UcNvMUESraceiAfVyRMAovlQBGs6\n9kBRm7DHYBUXYC2ABQoJbQRLDr/1B5JPf/M8+Qd7BKu8tcDC03U01SMHFLpO\naOs/HLXcDxtnnpL07tGVsm0zhMc5N8tq4/L3SHxK7Vi+TacwQzI="
