language: ruby
sudo: false
script: 'ci/travis.rb'
before_install:
  - "rvm current | grep 'jruby' && export AR_JDBC=true || echo"
before_script:
  - bundle update
cache: bundler
env:
  global:
    - JRUBY_OPTS='-J-Xmx1024M'
  matrix:
    - "GEM=railties"
    - "GEM=ap"
    - "GEM=aj"
    - "GEM=am,amo,as,av"
    - "GEM=ar:mysql"
    - "GEM=ar:mysql2"
    - "GEM=ar:sqlite3"
    - "GEM=ar:postgresql"
    - "GEM=aj:integration"
rvm:
  - 2.2
  - ruby-head
  - rbx-2
  - jruby
matrix:
  allow_failures:
    - env: "GEM=ar:mysql"
    - rvm: rbx-2
    - rvm: jruby
    - env: "GEM=aj"
    - env: "GEM=aj:integration"
  fast_finish: true
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "YA1alef1ESHWGFNVwvmVGCkMe4cUy4j+UcNvMUESraceiAfVyRMAovlQBGs6\n9kBRm7DHYBUXYC2ABQoJbQRLDr/1B5JPf/M8+Qd7BKu8tcDC03U01SMHFLpO\naOs/HLXcDxtnnpL07tGVsm0zhMc5N8tq4/L3SHxK7Vi+TacwQzI="
bundler_args: --without test
services:
  - memcached
  - redis
  - rabbitmq
addons:
  postgresql: "9.3"
