language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
  - rbx-2
  - jruby

sudo: false

services:
  - memcached
  - redis
  - rabbitmq

addons:
  postgresql: "9.3"

env:
  global:
    - JRUBY_OPTS='-J-Xmx1024M'
  matrix:
    - "GEM=railties"
    - "GEM=ap"
    - "GEM=am,amo,as,av,aj"
    - "GEM=ar:mysql"
    - "GEM=ar:mysql2"
    - "GEM=ar:sqlite3"
    - "GEM=ar:postgresql"
    - "GEM=aj:integration"

bundler_args: --path vendor/bundle --without test

before_install: "rvm current | grep 'jruby' && export AR_JDBC=true || echo"

script: 'ci/travis.rb'

matrix:
  allow_failures:
    - rvm: 1.9.3
      env: "GEM=ar:mysql"
    - rvm: 2.0.0
      env: "GEM=ar:mysql"
    - rvm: ruby-head
      env: "GEM=ar:mysql"
    - rvm: rbx-2
    - rvm: jruby
  fast_finish: true

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "YA1alef1ESHWGFNVwvmVGCkMe4cUy4j+UcNvMUESraceiAfVyRMAovlQBGs6\n9kBRm7DHYBUXYC2ABQoJbQRLDr/1B5JPf/M8+Qd7BKu8tcDC03U01SMHFLpO\naOs/HLXcDxtnnpL07tGVsm0zhMc5N8tq4/L3SHxK7Vi+TacwQzI="

